# This playbook assumes that cyverse-ez directory is located in /opt/cyverse-ez/

- name: this playbook will setup ez locally
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: pull in any Ansible Galaxy roles from the requirements.yml
      command: ansible-galaxy install -r /opt/cyverse-ez/requirements.yml

    - name: including the git role
      static: no
      include_role:
        name: git

    - name: including cyverse ez role
      static: no
      include_role:
        name: ez
