# This playbook assumes that cyverse-ez directory is located in /opt/cyverse-ez/

- name: this playbook will setup ez locally
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: include variables found in /etc/cyverse/ez.yml, if it exists; if error, just ignore
      include_vars:
        file: /etc/cyverse/ez.yml
      ignore_errors: yes

    - name: remove the ez role if update is forced
      command: ansible-galaxy remove ez
      when: ez_force_update is defined

    - name: pull in any Ansible Galaxy roles from the requirements.yml
      command: ansible-galaxy install -r /opt/cyverse-ez/requirements.yml

    - name: logfile for ansible-pulls, let's touch it and set the right permissions
      file:
       path: /var/log/cyverse-ez.log 
       state: touch
       mode: 0777

    - name: including cyverse ez role
      static: no
      include_role:
        name: ez
